Add support for relative $schema paths
ota-meshi/eslint-plugin-json-schema-validator pull request #155
Opened 2022-07-08 18:12 UTC by nspire909

I also fixed an issue with the tests. The filename being passed in to eslint by the tests was only a partial path in most circumstances, and this fix needs `context.getFilename()` to return a full path. I'm not very familiar with eslint, so if there is a better way to do this, let me know.

2022-07-08 18:54 UTC, JounQin requested changes

2022-07-08 18:54 UTC, JounQin commented on src/rules/no-invalid.ts
> +                            getPhysicalFilename(context.getFilename()),
Should prefer `context.getPhysicalFilename()` if it's available.

2022-07-08 18:58 UTC, JounQin commented on src/rules/no-invalid.ts
> +                            getPhysicalFilename(context.getFilename()),
```suggestion
                            typeof context.getPhysicalFilename === 'function' ? context.getPhysicalFilename() : getPhysicalFilename(context.getFilename()),
```

2022-07-08 22:53 UTC, ota-meshi approved these changes
LGTM! Thank you!

2022-07-09 00:11 UTC, JounQin approved these changes
LGTM

2022-07-09 01:03 UTC, merged